### ISSUE TITLE
Initialize the node-express project

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/template_engines_assignment#1]
### Goal

We want to initialize the node-express project so we can start building our application

### Tasks

- [ ] Initialize the node-express project with `npm init `
- [ ] Install express.js framework, ejs templating engine and nodemon
- [ ] create a basic  web server using express
- [ ] test the application
